Project NBTC_VDO_WALL {
  database_type: 'MSSQL'
  Note: '''
    # NBTC_VDO_WALL Database
    **markdown content here**
  '''
}

Table "dbo"."Area_Province" {
  "id" int [not null, increment,note: 'ID ของจังหวัดภายในแต่ละเขตของกสทช.']
  "area_id" int [not null,note: 'ID ของเขตในกสทช. (FK)']
  "geography_id" int [not null,note: 'ID รหัสภูมิภาคประเทศ (FK)']
  "province_id" int [not null,note: 'ID รหัสจังหวัด (FK)']
  "is_office" bit [not null,note: 'เป็นที่ตั้งสำนักงานเขต?']
  "created_by" nvarchar(50) [note: 'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [note: 'วันที่ที่สร้างข้อมูล']
  "modifed_by" nvarchar(50) [note: 'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [note: 'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [note: 'ชื่อของผู้ลบข้อมูล']
  "deleted_date" datetime [note: 'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note: 'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']

Indexes {
  id [pk]
}
}

Table "dbo"."Disturbance_Report" {
  "id" bigint [not null, increment,note:'ID. ของ Disturbance_Report']
  "region_id" int [not null,note:'ID. ของ Region (FK.)']
  "area_id" int [not null,note:'ID ของ Area (FK.)']
  "person_responsible" nvarchar(50) [note:'ชื่อของผู้รับผิดชอบ']
  "report_year" int [note:'ปีของข้อมูลการรบกวน']
  "report_month" int [note:'เดือนของข้อมูลการรบกวน']
  "quarter" int [note:'ไตรมาสของข้อมูลการรบกวน']
  "agency_name" nvarchar(50) [note:'ชื่อของหน่วยงาน']
  "received_date" datetime [note:'วันที่หนังสือ']
  "received_no" nvarchar(50) [note:'เลขที่หนังสือ']
  "business_type_id" int [not null,note:'ID. ของ Business_Type (FK.)']
  "business_type_name" nvarchar(100) [note:'ชื่อของประเภทหน่วยงาน']
  "disturbance_type_id" int [note:'ID. ของ Disturbance_Type (FK.)']
  "disturbance_type_name" nvarchar(100) [note:'ชื่อของประเภทการรบกวน']
  "description" ntext [note:'รายละเอียดของแจ้งปัญหาการรบกวน']
  "site_code" nvarchar(20) [note:'รหัสของ site ที่แจ้งปัญหา']
  "latitude" nvarchar(20) [note:'ละติจูดของสถานที่ที่แจ้งปัญหา']
  "longitude" nvarchar(20) [note:'ลองจิจูดของสถานที่ที่แจ้งปัญหา']
  "sub_district_id" int [note:'ID. ของ Sub_District (FK.)']
  "sub_district_name" nvarchar(50) [note:'ชื่อของตำบล / แขวง']
  "district_id" int [note:'ID. ของ District (FK.)']
  "district_name" nvarchar(50) [note:'ชื่อของอำเภอ / เขต']
  "province_id" int [note:'ID. ของ Province (FK.)']
  "province_name" nvarchar(50) [note:'ชื่อของจังหวัด']
  "cause_of_disturbance" ntext [note:'สาเหตุของการรบกวน']
  "frequency" int [note:'ความถี่ (MHz.)']
  "disturbance_status_id" int [not null,note:'ID ของ Disturbance_Status ( FK.)']
  "cloesd_no" nvarchar(20) [note:'เลขหนังสือปิดงาน']
  "closed_date" datetime [note:'วันที่ที่ปิดงาน']
  "duration" int [note:'ระยะเวลาในการดำเนินการ (วัน) : วันที่ปิด - วันที่รับเรื่อง']
  "closed_description" ntext [note:'รายละเอียดในการปิดงาน']
  "created_by" nvarchar(50) [note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [note:'วันที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [note:'วันที่ที่ปรับปรุงข้อมูล']
  "status" varchar(1) [note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']

Indexes {
  id [pk]
}
}

Table "dbo"."EMF_Measurement_Report" {
  "id" bigint [not null, increment,note:'ID. ของ EMF Measurement Report']
  "report_year" int [not null,note:'ปีของข้อมูลการตรวจวัด']
  "report_month" int [not null,note:'เดือนของข้อมูลการตรวจวัด']
  "report_date" int [not null,note:'วันที่ของข้อมูลการตรวจวัด']
  "quarter" int [not null,note:'ไตรมาสของข้อมูลการตรวจวัด']
  "selection" nvarchar(100) [note:'']
  "measured_time" datetime [note:'ชื่อ Service ของข้อมูลการตรวจวัด']
  "service_name" nvarchar(50) [note:'ความถี่ (Hz) เริ่มต้นที่ทำการตรวจวัด']
  "start_Hz" int [note:'ความถี่ (Hz) สิ้นสุดที่ทำการตรวจวัด']
  "stop_Hz" int [note:'ความถี่ (Hz) สิ้นสุดที่ทำการตรวจวัด']
  "original_file_name" nvarchar(100) [note:'ชื่อของไฟล์ต้นฉบับที่นำเข้าข้อมูล']
  "new_file_name" nvarchar(100) [note:'ชื่อของไฟล์ที่นำเข้าข้อมูลสำเร็จ อัพเดทชื่อใหม่ ต่อท้ายด้วย_yyMMddHHmm']
  "files_path" nvarchar(500) [note:'ชื่อ path ที่เก็บไฟล์หลังจากนำเข้าข้อมูลสำเร็จหรือ Fail(แยกเก็บ)']
  "created_date" datetime [note:'วันเวลาที่สร้างข้อมูล']

Indexes {
  id [pk]
}
}

Table "dbo"."EMF_Measurement_Report_Detail" {
  "id" bigint [not null, increment,note:'ID. ของ EMF_Measurement_Report_Detail']
  "emf_measurement_report_id" bigint [not null,note:'ID. ของ EMF_Measurement_Report (FK.)']
  "max_V/m" decimal(20,2) [note:'ค่า Max ของการตรวจวัดโดยคำนวณจาก V/m']
  "avg_V/m" decimal(20,2) [note:'ค่า Avg ของการตรวจวัดโดยคำนวณจาก V/m']
  "rms_V/m" decimal(20,2) [note:'ค่า Rms ของการตรวจวัดโดยคำนวณจาก V/m']
  "limit_V/m" decimal(20,2) [note:'ค่า Limit ของการตรวจวัดโดยคำนวณจาก V/m']
  "max_percent" decimal(20,2) [note:'ค่า Max ของการตรวจวัดแบบ %']
  "avg_percent" decimal(20,2) [note:'ค่า Avg ของการตรวจวัดแบบ %']
  "rms_percent" decimal(20,2) [note:'ค่า Rms ของการตรวจวัดแบบ %']
  "max_mA/m" decimal(20,2) [note:'ค่า Max ของการตรวจวัดโดยคำนวณจาก mA/m']
  "avg_mA/m" decimal(20,2) [note:'ค่า Avg ของการตรวจวัดโดยคำนวณจาก mA/m']
  "rms_mA/m" decimal(20,2) [note:'ค่า Rms ของการตรวจวัดโดยคำนวณจาก mA/m']
  "max_mW/m" decimal(20,2) [note:'ค่า Max ของการตรวจวัดโดยคำนวณจาก mW/m']
  "avg_mW/m" decimal(20,2) [note:'ค่า Avg ของการตรวจวัดโดยคำนวณจาก mW/m']
  "rms_mW/m" decimal(20,2) [note:'ค่า Rms ของการตรวจวัดโดยคำนวณจาก mW/m']
  "created_date" datetime [note:'วันเวลาที่สร้างข้อมูล']

Indexes {
  id [pk]
}
}

Table "dbo"."Health_Safety_Test_Plan" {
  "id" bigint [not null, increment,note:'']
  "region_id" int [not null,note:'ID. ของ Region (FK.)']
  "area_id" int [not null,note:'ID. ของ Area (FK.)']
  "report_year" int [not null,note:'ปีของข้อมูลแผนการดำเนินการ']
  "description" nvarchar(50) [note:'คำอธิบาย']
  "actual_01" int [note:'แผนการทดสอบเดือน ม.ค.']
  "result_01" int [note:'ผลการทดสอบเดือน ม.ค.']
  "actual_02" int [note:'แผนการทดสอบเดือน ก.พ.']
  "result_02" int [note:'ผลการทดสอบเดือน ก.พ.']
  "actual_03" int [note:'แผนการทดสอบเดือน มี.ค.']
  "result_03" int [note:'ผลการทดสอบเดือน มี.ค.']
  "actual_04" int [note:'แผนการทดสอบเดือน เม.ย.']
  "result_04" int [note:'ผลการทดสอบเดือน เม.ย.']
  "actual_05" int [note:'แผนการทดสอบเดือน พ.ค.']
  "result_05" int [note:'ผลการทดสอบเดือน พ.ค.']
  "actual_06" int [note:'แผนการทดสอบเดือน มิ.ย.']
  "result_06" int [note:'ผลการทดสอบเดือน มิ.ย.']
  "actual_07" int [note:'แผนการทดสอบเดือน ก.ค.']
  "result_07" int [note:'ผลการทดสอบเดือน ก.ค.']
  "actual_08" int [note:'แผนการทดสอบเดือน ส.ค.']
  "result_08" int [note:'ผลการทดสอบเดือน ส.ค.']
  "actual_09" int [note:'แผนการทดสอบเดือน ก.ย.']
  "result_09" int [note:'ผลการทดสอบเดือน ก.ย.']
  "actual_10" int [note:'แผนการทดสอบเดือน ต.ค.']
  "result_10" int [note:'ผลการทดสอบเดือน ต.ค.']
  "actual_11" int [note:'แผนการทดสอบเดือน พ.ย.']
  "result_11" int [note:'ผลการทดสอบเดือน พ.ย.']
  "actual_12" int [note:'แผนการทดสอบเดือน ธ.ค.']
  "result_12" int [note:'ผลการทดสอบเดือน ธ.ค.']
  "original_file_name" nvarchar(100) [note:'ชื่อของไฟล์ต้นฉบับที่นำเข้าข้อมูล']
  "new_file_name" nvarchar(100) [note:'ชื่อของไฟล์ที่นำเข้าข้อมูลสำเร็จ อัพเดทชื่อใหม่ ต่อท้ายด้วย_yyMMddHHmm']
  "file_path" nvarchar(500) [note:'ชื่อ path ที่เก็บไฟล์หลังจากนำเข้าข้อมูลสำเร็จหรือ Fail(แยกเก็บ)']
  "created_by" nvarchar(50) [note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" int [note:'วันเวลาที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [note:'ชื่อของผู้แก้ไขข้อมูล']
  "modified_date" int [note:'วันเวลาที่แก้ไขข้อมูล']

Indexes {
  id [pk]
}
}

Table "dbo"."Info_Area" {
  "id" int [not null, increment,note:'ID. ของเขตพื้นที่ในกสทช.']
  "region_id" int [not null,note:'ID. ของภาคในกสทช. (FK.)']
  "name_th" nvarchar(50) [not null,note:'ชื่อภาษาไทยของพื้นที่ในกสทช.']
  "name_en" nvarchar(50) [note:'ชื่อภาษาอังกฤษของพื้นที่ในกสทช.']
  "created_by" nvarchar(50) [note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [note:'วันที่สร้างข้อมูล']
  "modifed_by" nvarchar(50) [note:'ชื่อของผู้แก้ไขข้อมูล']
  "modified_date" datetime [note:'วันเวลาที่แก้ไขข้อมูล']
  "deleted_by" nvarchar(50) [note:'ชื่อของผู้ลบข้อมูล']
  "deleted_date" datetime [note:'วันเวลาที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']

Indexes {
  id [pk]
}
}

Table "dbo"."Info_Broadcast_Station" {
  "id" bigint [not null, increment,note:'ID. ของสถานีวิทยุ']
  "chk_ID" int [note:'รหัส ChkID']
  "transaction_date" datetime [note:'วันที่ของข้อมูล']
  "checked_date" datetime [note:'วันที่ที่ตรวจสอบ']
  "region_id" int [note:'รหัสของภาคในกสทช. (FK.)']
  "region_name" nvarchar(50) [note:'ชื่อของภาคในกสทช.']
  "area_id" int [note:'รหัสของเขตในกสทช. (FK.)']
  "area_name" nvarchar(50) [note:'ชื่อของเขตในกสทช']
  "station" nvarchar(50) [note:'ลักษณะของสถานี']
  "station_type_id" int [note:'ID. ของประเภทสถานี (FK.)']
  "station_type_name" nvarchar(50) [note:'ชื่อของประเภทของสถานี']
  "station_code" nvarchar(10) [note:'รหัสของสถานี']
  "station_name" nvarchar(100) [note:'ชื่อของสถานี']
  "frequency" decimal(10,4) [note:'ความถี่ (MHz)']
  "license_no" nvarchar(20) [note:'เลขที่ใบอนุญาต']
  "province_id" int [note:'รหัสของจังหวัด (FK.)']
  "province_name" nvarchar(50) [note:'ชื่อของจังหวัด']
  "district_id" int [note:'รหัสของอำเภอ / เขต (FK.)']
  "district_name" nvarchar(50) [note:'ขื่อของอำเภอ / เขต']
  "sub_district_id" int [note:'รหัสของตำบล / แขวง']
  "sub_district_name" nvarchar(50) [note:'ชื่อของตำบล / แขวง']
  "address" nvarchar(500) [note:'ที่ตั้งของสถานี']
  "latitude" nvarchar(20) [note:'ละติจูดของสถานี']
  "longitude" nvarchar(20) [note:'ลองจิจูดของสถานี']
  "tested_result" ntext [note:'ผลการทดสอบ']
  "station_status" nvarchar(50) [note:'สถานะของสถานี']
  "broadcase_start_time" time [note:'ระยะเวลาเริ่มต้นการออกอากาศ']
  "broadcast_end_time" time [note:'ระยะเวลาสิ้นสุดการออกอากาศ']
  "created_by" nvarchar(50) [note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [note:'วันที่ที่สร้างข้อมูล']
  "modifed_by" nvarchar(50) [note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [note:'ชื่อของผู้ลบข้อมูล']
  "deleted_date" datetime [note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']

Indexes {
  id [pk]
}
}

Table "dbo"."Info_Business_Type" {
  "id" int [not null, increment,note:'ID. ของประเภทกิจการ']
  "name_th" nvarchar(100) [not null,note:'ชื่อภาษาไทยของประเภทกิจการ']
  "name_en" nvarchar(100) [note:'ชื่อภาษาอังกฤษของประเภทกิจการ']
  "created_by" nvarchar(50) [note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [note:'วันที่ที่สร้างข้อมูล']
  "modifed_by" nvarchar(50) [note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [note:'ชื่อของผู้บข้อมูล']
  "deleted_date" datetime [note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']

Indexes {
  id [pk]
}
}

Table "dbo"."Info_Company_Type" {
  "id" int [not null, increment,note:'ID. ของประเภทหน่วยงาน']
  "name_th" nvarchar(100) [not null,note:'ชื่อภาษาไทยของประเภทหน่วยงาน']
  "name_en" nvarchar(100) [note:'ชื่อภาษาอังกฤษของประเภทหน่วยงาน']
  "created_by" nvarchar(50) [note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [note:'วันที่ที่สร้างข้อมูล']
  "modifed_by" nvarchar(50) [note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [note:'ชื่อของผู้บข้อมูล']
  "deleted_date" datetime [note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']

Indexes {
  id [pk]
}
}

Table "dbo"."Info_District" {
  "id" int [not null, increment,note:'ID. ของอำเภอ / เขต']
  "province_id" int [not null,note:'ID. ของจังหวัด (FK.)']
  "name_th" nvarchar(50) [not null,note:'ชื่อภาษาไทยของอำเภอ / เขต']
  "name_en" nvarchar(50) [note:'ชื่อภาษาอังกฤษของอำเภอ / เขต']
  "created_by" nvarchar(50) [note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [note:'วันที่ที่สร้างข้อมูล']
  "modifed_by" nvarchar(50) [note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [note:'ชื่อของผู้สร้างข้อมูล']
  "deleted_date" datetime [note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']

Indexes {
  id [pk]
}
}

Table "dbo"."Info_Disturbance_Status" {
  "id" int [not null, increment,note:'ID. ของสถานะการรบกวน']
  "name_th" nvarchar(100) [not null,note:'ชื่อภาษาไทยของสถานะการรบกวน']
  "name_en" nvarchar(100) [note:'ชื่อภาษาอังกฤษของสถานะการรบกวน']
  "created_by" nvarchar(50) [note:'ชื่อของผูสร้างข้อมูล']
  "created_date" datetime [note:'วันที่ที่สร้างข้อมูล']
  "modifed_by" nvarchar(50) [note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [note:'ชื่อของผู้ลบข้อมูล']
  "deleted_date" datetime [note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']

Indexes {
  id [pk]
}
}

Table "dbo"."Info_Disturbance_Type" {
  "id" int [not null, increment,note:'ID. ของประเภทการรบกวน']
  "name_th" nvarchar(100) [not null,note:'ชื่อภาษาไทยของประเภทการรบกวน']
  "name_en" nvarchar(100) [note:'ชื่อภาษาอังกฤษของประเภทการรบกวน']
  "created_by" nvarchar(50) [note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [note:'วันที่ที่สร้างข้อมูล']
  "modifed_by" nvarchar(50) [note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [note:'ชื่อของผู้ลบข้อมูล']
  "deleted_date" datetime [note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']

Indexes {
  id [pk]
}
}

Table "dbo"."Info_Geography" {
  "id" int [not null, increment,note:'ID. ของภาคในกสทช.']
  "name_th" nvarchar(50) [not null,note:'ชื่อภาษาไทยของภาคในกสทช.']
  "name_en" nvarchar(50) [note:'ชื่อภาษาอังกฤษของภาคในกสทช.']
  "created_by" nvarchar(50) [note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [note:'วันที่ที่สร้างข้อมูล']
  "modifed_by" nvarchar(50) [note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [note:'ชื่อของผู้ลบข้อมูล']
  "deleted_date" datetime [note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']

Indexes {
  id [pk]
}
}

Table "dbo"."Info_License_Type" {
  "id" int [not null, increment,note:'ID. ของประเภท.ใบอนุญาต']
  "name_th" nvarchar(100) [not null,note:'ชื่อภาษาไทยของประเภทใบอนุญาต']
  "name_en" nvarchar(100) [note:'ชื่อภาษาอังกฤษของประเภทใบอนุญาต']
  "created_by" nvarchar(50) [note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [note:'วันที่ที่สร้างข้อมูล']
  "modifed_by" nvarchar(50) [note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [note:'ชื่อของผู้บข้อมูล']
  "deleted_date" datetime [note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']

Indexes {
  id [pk]
}
}

Table "dbo"."Info_Other_Station" {
  "id" bigint [not null, increment,note:'ID. ของสถานี']
  "owner_type_id" int [note:'ID. ของประเภทผู้ครอบครอง (FK.)']
  "owner_type_name" nvarchar(100) [note:'ชื่อของประเภทผู้ครอบครอง']
  "region_id" int [note:'รหัสของภาคในกสทช. (FK.)']
  "region_name" nvarchar(50) [note:'ชื่อของภาคในกสทช.']
  "area_id" int [note:'รหัสของเขตในกสทช. (FK.)']
  "area_name" nvarchar(50) [not null,note:'ชื่อของเขตในกสทช.']
  "station_type_id" int [not null,note:'ID. ของประเภทสถานี (FK.)']
  "station_type_name" nvarchar(50) [not null,note:'ชื่อของประเภทสถานี']
  "station_code" nvarchar(10) [not null,note:'รหัสของสถานี']
  "station_name" nvarchar(100) [not null,note:'ชื่อของสถานี']
  "frequency" nvarchar(50) [not null,note:'ความถี่ (MHz)']
  "ฺbusiness_name" nvarchar(255) [not null,note:'ชื่อของผู้ประกอบการ']
  "company_type_id" int [not null,note:'ID. ของประเภทหน่วยงาน (FK.)']
  "company_type_name" nvarchar(100) [not null,note:'ชื่อของประเภทหน่วยงาน']
  "license_type_id" int [not null,note:'ID. ของประเภทใบอนุญาต (FK.)']
  "license_type_name" nvarchar(100) [not null,note:'ชื่อของประเภทใบอนุญาต']
  "license_no" nvarchar(20) [not null,note:'เลขที่ใบอนุญาต']
  "license_date" datetime [not null,note:'วันที่ที่ออกใบอนุญาต']
  "province_id" int [not null,note:'รหัสของจังหวัด (FK.)']
  "province_name" nvarchar(50) [not null,note:'ชื่อของจังหวัด']
  "district_id" int [not null,note:'รหัสของอำเภอ / เขต (FK.)']
  "district_name" nvarchar(50) [not null,note:'ขื่อของอำเภอ / เขต']
  "sub_district_id" int [not null,note:'รหัสของตำบล / แขวง']
  "sub_district_name" nvarchar(50) [not null,note:'ชื่อของตำบล / แขวง']
  "address" nvarchar(500) [not null,note:'ที่ตั้งของสถานี']
  "latitude" nvarchar(20) [not null,note:'ละติจูดของสถานี']
  "longitude" nvarchar(20) [not null,note:'ลองจิจูดของสถานี']
  "contract_name" nvarchar(100) [not null,note:'ชื่อผู้ประสานงาน']
  "contract_telephone" nvarchar(50) [not null,note:'เบอร์โทรสำหรับติดต่อ']
  "altitude_above_sea_level" int [not null,note:'ความสูงจากระดับน้ำทะเล (M)']
  "aerial_type" nvarchar(100) [not null,note:'ชนิดสายอากาศ']
  "expansion_rate_of_aerial" decimal(10,2) [not null,note:'อัตราการขยายเสาอากาศ (DBI)']
  "sending" int [not null,note:'กำลังส่ง (W)']
  "HeightOfAerial" int [not null,note:'ความสูงของเสาอากาศ (M)']
  "TestOfFrequency" decimal(10,4) [not null,note:'ความถี่ที่วัดได้ (MHz)']
  "broadcast_start_time" time [not null,note:'ระยะเวลาเริ่มต้นการออกอากาศ']
  "broadcast_end_time" time [not null,note:'ระยะเวลาสิ้นสุดการออกอากาศ']
  "CreatedBy" nvarchar(50) [not null,note:'ชื่อของผู้สร้างข้อมูล']
  "CreatedDate" datetime [not null,note:'วันที่ที่สร้างข้อมูล']
  "ModifedBy" nvarchar(50) [not null,note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "ModifiedDate" datetime [not null,note:'วันที่ที่ปรับปรุงข้อมูล']
  "DeletedBy" nvarchar(50) [not null,note:'ชื่อของผู้บข้อมูล']
  "DeletedDate" datetime [not null,note:'วันที่ที่ลบข้อมูล']
  "Status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']

Indexes {
  id [pk]
}
}

Table "dbo"."Info_Owner_Type" {
  "id" int [not null, increment,note:'ID. ของประเภทผู้ครอบครอง']
  "name_th" nvarchar(100) [not null,note:'ชื่อภาษาไทยของประเภทผู้ครอบครอง']
  "name_en" nvarchar(100) [not null,note:'ชื่อภาษาอังกฤษของประเภทผู้ครอบครอง']
  "created_by" nvarchar(50) [not null,note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [not null,note:'วันที่ที่สร้างข้อมูล']
  "modifed_by" nvarchar(50) [not null,note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [not null,note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [not null,note:'ชื่อของผู้ลบข้อมูล']
  "deleted_date" datetime [not null,note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']

Indexes {
  id [pk]
}
}

Table "dbo"."Info_Province" {
  "id" int [not null, increment,note:'ID. ของจังหวัด']
  "geography_id" int [not null,note:'ID. ของภูมิภาค (FK.)']
  "name_th" nvarchar(50) [not null,note:'ชื่อภาษาไทยของจังหวัด']
  "name_en" nvarchar(50) [not null,note:'ชื่อภาษาอังกฤษของจังหวัด']
  "created_by" nvarchar(50) [not null,note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [not null,note:'วันที่ที่สร้างข้อมูล']
  "modifed_by" nvarchar(50) [not null,note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [not null,note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [not null,note:'ชื่อของผู้ลบข้อมูล']
  "deleted_date" datetime [not null,note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']

Indexes {
  id [pk]
}
}

Table "dbo"."Info_Radio_Station" {
  "id" int [not null, increment,note:'ID. ของสถานีวิทยุการจายเสียง']
  "name_th" nvarchar(50) [not null,note:'ชื่อภาษาไทยของสถานีวิทยุการจายเสียง']
  "name_en" nvarchar(50) [not null,note:'ชื่อภาษาอังกฤษของสถานีวิทยุการจายเสียง']
  "station_unit" nvarchar(10) [not null,note:'หน่วยนับของสถานีวิทยุการจายเสียง']
  "created_by" nvarchar(50) [not null,note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [not null,note:'วันที่ที่สร้างข้อมูล']
  "modifed_by" nvarchar(50) [not null,note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [not null,note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [not null,note:'ชื่อของผู้ลบข้อมูล']
  "deleted_date" datetime [not null,note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']

Indexes {
  id [pk]
}
}

Table "dbo"."Info_Region" {
  "id" int [not null, increment,note:'ID. ของภาคในกสทช.']
  "name_th" nvarchar(50) [not null,note:'ชื่อภาษาไทยของภาคในกสทช']
  "name_en" nvarchar(50) [not null,note:'ชื่อภาษาอังกฤษของภาคในกสทช']
  "created_by" nvarchar(50) [not null,note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [not null,note:'วันที่ที่สร้างข้อมูล']
  "modifed_by" nvarchar(50) [not null,note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [not null,note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [not null,note:'ชื่อของผู้ลบข้อมูล']
  "deleted_date" datetime [not null,note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']

Indexes {
  id [pk]
}
}

Table "dbo"."Info_Station_Type" {
  "id" int [not null, increment,note:'ID. ของประเภทสถานี']
  "name_th" nvarchar(100) [not null,note:'ชื่อภาษาไทยของประเภทสถานี']
  "name_en" nvarchar(100) [not null,note:'ชื่อภาษาอังกฤษของประเภทสถานี']
  "created_by" nvarchar(50) [not null,note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [not null,note:'วันที่ที่สร้างข้อมูล']
  "modifed_by" nvarchar(50) [not null,note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [not null,note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [not null,note:'ชื่อของผู้บข้อมูล']
  "deleted_date" datetime [not null,note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']

Indexes {
  id [pk]
}
}

Table "dbo"."Info_Sub_District" {
  "id" int [not null, increment,note:'ID. ของตำบล / แขวง']
  "province_id" int [not null,note:'ID. ของจังหวัด (FK.)']
  "district_id" int [not null,note:'ID. ของอำเภอ / เขต (FK.)']
  "name_th" nvarchar(50) [not null,note:'ชื่อภาษาไทยของตำบล / แขวง']
  "name_en" nvarchar(50) [not null,note:'ชื่อภาษาอังกฤษของตำบล / แขวง']
  //"post_code" varchar(5) [not null,note:'รหัสไปรษณีย์']
  "created_by" nvarchar(50) [not null,note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [not null,note:'วันที่ที่สร้างข้อมูล']
  "modifed_by" nvarchar(50) [not null,note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [not null,note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [not null,note:'ชื่อของผู้ลบข้อมูล']
  "deleted_date" datetime [not null,note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']

Indexes {
  id [pk]
}
}

Table "dbo"."Info_Zipcode" {
  "id" int [not null, increment,note:'ID. ของรหัสไปรษณีย์']
  "province_id" int [not null,note:'ID. ของจังหวัด (FK.)']
  "district_id" int [not null,note:'ID. ของอำเภอ (FK.)']
  "sub_district_id" int [not null,note:'ID. ของตำบล / แขวง (FK.)']
  "code" varchar(5) [not null,note:'รหัสไปรษณีย์']
  "created_by" nvarchar(50) [not null,note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [not null,note:'วันที่ที่สร้างข้อมูล']
  "modifed_by" nvarchar(50) [not null,note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [not null,note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [not null,note:'ชื่อของผู้ลบข้อมูล']
  "deleted_date" datetime [not null,note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']

Indexes {
  id [pk]
}
}

Table "dbo"."Radio_Emission_Test_Plan" {
  "id" bigint [not null, increment,note:'ID. ของ EMF Measurement Report']
  "region_id" int [not null,note:'ID. ของ Region (FK.)']
  "area_id" int [not null,note:'ID. ของ Area (FK.)']
  "report_year" int [not null,note:'ปีของข้อมูลแผนการดำเนินการ']
  "radio_station_id" int [not null,note:'ID. ของ Radion_Station (FK.)']
  "actual_01" int [not null,note:'แผนการทดสอบเดือน ม.ค.']
  "result_01" int [not null,note:'ผลการทดสอบเดือน ม.ค.']
  "actual_02" int [not null,note:'แผนการทดสอบเดือน ก.พ.']
  "result_02" int [not null,note:'ผลการทดสอบเดือน ก.พ.']
  "actual_03" int [not null,note:'แผนการทดสอบเดือน มี.ค.']
  "result_03" int [not null,note:'ผลการทดสอบเดือน มี.ค.']
  "actual_04" int [not null,note:'แผนการทดสอบเดือน เม.ย.']
  "result_04" int [not null,note:'ผลการทดสอบเดือน เม.ย.']
  "actual_05" int [not null,note:'แผนการทดสอบเดือน พ.ค.']
  "result_05" int [not null,note:'ผลการทดสอบเดือน พ.ค.']
  "actual_06" int [not null,note:'แผนการทดสอบเดือน มิ.ย.']
  "result_06" int [not null,note:'ผลการทดสอบเดือน มิ.ย.']
  "actual_07" int [not null,note:'แผนการทดสอบเดือน ก.ค.']
  "result_07" int [not null,note:'ผลการทดสอบเดือน ก.ค.']
  "actual_08" int [not null,note:'แผนการทดสอบเดือน ส.ค.']
  "result_08" int [not null,note:'ผลการทดสอบเดือน ส.ค.']
  "actual_09" int [not null,note:'แผนการทดสอบเดือน ก.ย.']
  "result_09" int [not null,note:'ผลการทดสอบเดือน ก.ย.']
  "actual_10" int [not null,note:'แผนการทดสอบเดือน ต.ค.']
  "result_10" int [not null,note:'ผลการทดสอบเดือน ต.ค.']
  "actual_11" int [not null,note:'แผนการทดสอบเดือน พ.ย.']
  "result_11" int [not null,note:'ผลการทดสอบเดือน พ.ย.']
  "actual_12" int [not null,note:'แผนการทดสอบเดือน ธ.ค.']
  "result_12" int [not null,note:'ผลการทดสอบเดือน ธ.ค.']
  "original_file_name" nvarchar(100) [not null,note:'ชื่อของไฟล์ต้นฉบับที่นำเข้าข้อมูล']
  "new_file_name" nvarchar(100) [not null,note:'ชื่อของไฟล์หลังจากที่นำเข้าข้อมูล']
  "file_path" nvarchar(500) [not null,note:'ชื่อ path ที่เก็บไฟล์หลังจากนำเข้าข้อมูล']
  "created_by" nvarchar(50) [not null,note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" int [not null,note:'วันที่ที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [not null,note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" int [not null,note:'วันที่ที่ปรับปรุงข้อมูล']

Indexes {
  id [pk]
}
}

Table "dbo"."TCI_Occupancy_Report" {
  "id" bigint [not null, increment,note:'ID. ของ TCI_Occupancy_Report']
  "report_year" int [not null,note:'ปีของข้อมูลการครอบครอง']
  "report_month" int [not null,note:'เดือนของข้อมูลการครอบครอง']
  "report_date" int [not null,note:'วันที่ของข้อมูลการครอบครอง']
  "quarter" int [not null,note:'ไตรมาสของข้อมูลการครอบครอง']
  "task_id" int [not null,note:'ค่า TaskID ของข้อมูลการครอบครอง']
  "storage_interval" nvarchar(20) [not null,note:'ค่า Storeage Interval ของข้อมูลการครอบครอง']
  "operator_id" nvarchar(100) [not null,note:'ค่า Operator ID. ของข้อมูลการครอบครอง']
  "message_length" int [not null,note:'ค่า Message Length ของข้อมูลการครอบครอง']
  "start_time" datetime [not null,note:'เวลาเริ่มต้นของของข้อมูลการครอบครอง']
  "stop_time" datetime [not null,note:'เวลาสิ้นสุดของข้อมูลการครอบครอง']
  "threshold_method" nvarchar(100) [not null,note:'ค่าของ ThresholdMethod']
  "duration" nvarchar(100) [not null,note:'ระยะเวลาในการดำเนินการ']
  "station_name" nvarchar(100) [not null,note:'ชื่อของสถานี']
  "all_single_channels" char(1) [not null,note:'ค่าของ AllSingleChannels (Y/N)']
  "latitude" nvarchar(20) [not null,note:'ละติจูดของสถานี']
  "longitude" nvarchar(20) [not null,note:'ลองจิจูดของสถานี']
  "antenna" nvarchar(50) [not null,note:'รายละเอียดของ Antenna']
  "polarization" nvarchar(20) [not null,note:'รายละเอียดของ Polarization']
  "original_file_name" nvarchar(100) [not null,note:'ชื่อของไฟล์ต้นฉบับที่นำเข้าข้อมูล']
  "new_file_name" nvarchar(100) [not null,note:'ชื่อของไฟล์หลังจากที่นำเข้าข้อมูล']
  "files_path" nvarchar(500) [not null,note:'ชื่อ path ที่เก็บไฟล์หลังจากนำเข้าข้อมูล']
  "created_date" datetime [not null,note:'วันที่ที่สร้างข้อมูล']

Indexes {
  id [pk]
}
}

Table "dbo"."TCI_Occupancy_Report_Detail" {
  "id" bigint [not null, increment,note:'ID. ของ TCI_Occupancy_Report_Detail']
  "tci_occupancy_report_id" bigint [not null,note:'ID. ของ TCI_Occupancy_Report (FK.)']
  "band" int [not null,note:'เลขของ Band ที่นำเข้าข้อมูล TCI']
  "start_frequency_MHz" int [not null,note:'ความถี่เริ่มต้นในการวัดผล (MHz)']
  "stop_frequency_MHz" int [not null,note:'ความถี่สิ้นสุดในการวัดผล (MHz)']
  "bandwidth_kHz" decimal(20,2) [not null,note:'ค่าของ Bandwidth (kHz)']
  "channel_no" int [not null,note:'หมายเลขของ Channel ที่ทำการตรวจวัด']
  "frequency_MHz" decimal(20,4) [not null,note:'ค่าของ Frequency(MHz)']
  "maximum_occupancy_percent" int [not null,note:'ค่าของ MaximumOccupancy %']
  "average_occupancy_percent" int [not null,note:'ค่าของ AverageOccupancy %']
  "maximum_field_strength_dBuV/m" int [not null,note:'ค่าของ MaximumFieldStrength(dBuV/m)']
  "average_field_strength_dBuV/m" int [not null,note:'ค่าของ AverageFieldStrength(dBuV/m)']
  "created_date" datetime [not null,note:'วันที่ที่สร้างข้อมูล']

Indexes {
  id [pk]
}
}

Ref "FKHealth_Saf953904":"dbo"."Info_Area"."id" < "dbo"."Health_Safety_Test_Plan"."area_id"

Ref "FKHealth_Saf855281":"dbo"."Info_Region"."id" < "dbo"."Health_Safety_Test_Plan"."region_id"

Ref "FKRadio_Emis890179":"dbo"."Info_Area"."id" < "dbo"."Radio_Emission_Test_Plan"."area_id"

Ref "FKRadio_Emis80993":"dbo"."Info_Region"."id" < "dbo"."Radio_Emission_Test_Plan"."region_id"

Ref "FKRadio_Emis238262":"dbo"."Info_Radio_Station"."id" < "dbo"."Radio_Emission_Test_Plan"."radio_station_id"

Ref "FKInfo_Zipco299713":"dbo"."Info_Province"."id" < "dbo"."Info_Zipcode"."province_id"

Ref "FKInfo_Zipco255546":"dbo"."Info_District"."id" < "dbo"."Info_Zipcode"."district_id"

Ref "FKArea_Provi574106":"dbo"."Info_Geography"."id" < "dbo"."Area_Province"."geography_id"

Ref "FKInfo_Sub_D858503":"dbo"."Info_Province"."id" < "dbo"."Info_Sub_District"."province_id"

Ref "FKInfo_Zipco177048":"dbo"."Info_Sub_District"."id" < "dbo"."Info_Zipcode"."sub_district_id" [update: cascade]

Ref "FKDisturbanc342409":"dbo"."Info_Business_Type"."id" < "dbo"."Disturbance_Report"."business_type_id"

Ref "FKDisturbanc708223":"dbo"."Info_Disturbance_Status"."id" < "dbo"."Disturbance_Report"."disturbance_status_id"

Ref "FKInfo_Sub_D902670":"dbo"."Info_District"."id" < "dbo"."Info_Sub_District"."district_id" [update: cascade]

Ref "FKInfo_Distr360426":"dbo"."Info_Province"."id" < "dbo"."Info_District"."province_id" [update: cascade]

Ref "FKInfo_Provi333697":"dbo"."Info_Geography"."id" < "dbo"."Info_Province"."geography_id" [update: cascade]

Ref "FKArea_Provi922664":"dbo"."Info_Province"."id" < "dbo"."Area_Province"."province_id" [update: cascade]

Ref "FKArea_Provi893606":"dbo"."Info_Area"."id" < "dbo"."Area_Province"."area_id"

Ref "FKDisturbanc670568":"dbo"."Info_Region"."id" < "dbo"."Disturbance_Report"."region_id"

Ref "FKInfo_Area396653":"dbo"."Info_Region"."id" < "dbo"."Info_Area"."region_id"

Ref "FKDisturbanc861381":"dbo"."Info_Area"."id" < "dbo"."Disturbance_Report"."area_id"

Ref "FKEMF_Measur160831":"dbo"."EMF_Measurement_Report"."id" < "dbo"."EMF_Measurement_Report_Detail"."emf_measurement_report_id"

Ref "FKTCI_Occupa427123":"dbo"."TCI_Occupancy_Report"."id" < "dbo"."TCI_Occupancy_Report_Detail"."tci_occupancy_report_id"
