Project NBTC_VDO_WALL {
  database_type: 'MSSQL'
  Note: '''Design for Microsoft SQL Server'
    # 
    **Version 1.0.1**
  '''
}

Table "dbo"."Area_Province" {
  "id" int [not null, increment,note: 'ID ของจังหวัดภายในแต่ละเขตของกสทช.']
  "area_id" int [not null,note: 'ID ของเขตในกสทช. (FK)']
  "geography_id" int [not null,note: 'ID รหัสภูมิภาคประเทศ (FK)']
  "province_id" int [not null,note: 'ID รหัสจังหวัด (FK)']
  "is_office" bit [not null,note: 'เป็นที่ตั้งสำนักงานเขต?']
  "created_by" nvarchar(50) [note: 'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [note: 'วันที่ที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [note: 'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [note: 'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [note: 'ชื่อของผู้ลบข้อมูล']
  "deleted_date" datetime [note: 'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note: 'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']
  note:"ตารางเก็บข้อมูลจังหวัดที่อยู่ภายในแต่ละเขต"
Indexes {
  id [pk]
}
}

Table "dbo"."Disturbance_Report" {
  "id" bigint [not null, increment,note:'ID. ของ Disturbance_Report']
  "region_id" int [not null,note:'ID. ของ Region (FK.)']
  "region_name" nvarchar(100) [not null,note:'ชื่อของภาคในกสทช.']
  "area_id" int [not null,note:'ID ของ Area (FK.)']
  "area_name" nvarchar(100) [not null,note:'ชื่อของเขต']
  "person_responsible" nvarchar(50) [note:'ชื่อของผู้รับผิดชอบ']
  "report_year" int [note:'ปีของข้อมูลการรบกวน']
  "report_month" int [note:'เดือนของข้อมูลการรบกวน']
  "report_quarter" int [note:'ไตรมาสของข้อมูลการรบกวน']
  "agency_name" nvarchar(50) [note:'ชื่อของหน่วยงาน']
  "received_date" datetime [note:'วันที่หนังสือ']
  "received_no" nvarchar(50) [note:'เลขที่หนังสือ']
  "business_type_id" int [not null,note:'ID. ของ Business_Type (FK.)']
  "business_type_name" nvarchar(100) [null,note:'ชื่อของประเภทหน่วยงาน']
  "disturbance_type_id" int [not null,note:'ID. ของ Disturbance_Type (FK.)']
  "disturbance_type_name" nvarchar(100) [null,note:'ชื่อของประเภทการรบกวน']
  "description" ntext [note:'รายละเอียดของแจ้งปัญหาการรบกวน']
  "site_code" nvarchar(20) [note:'รหัสของ site ที่แจ้งปัญหา']
  "latitude" decimal(12,9) [note:'ละติจูดของสถานที่ที่แจ้งปัญหา']
  "longitude" decimal(12,9) [note:'ลองจิจูดของสถานที่ที่แจ้งปัญหา']
  "sub_district_id" int [not null,note:'ID. ของ Sub_District (FK.)']
  "sub_district_name" nvarchar(50) [note:'ชื่อของตำบล / แขวง']
  "district_id" int [not null,note:'ID. ของ District (FK.)']
  "district_name" nvarchar(50) [note:'ชื่อของอำเภอ / เขต']
  "province_id" int [note:'ID. ของ Province (FK.)']
  "province_name" nvarchar(50) [note:'ชื่อของจังหวัด']
  "cause_of_disturbance" ntext [note:'สาเหตุของการรบกวน']
  "frequency" int [note:'ความถี่ (MHz.)']
  "disturbance_status_id" int [not null,note:'ID ของ Disturbance_Status ( FK.)']
  "disturbance_status_name" nvarchar(100) [null,note:'ชื่อสถานะของการรบกวน']
  "cloesd_no" nvarchar(20) [note:'เลขหนังสือปิดงาน']
  "closed_date" datetime [note:'วันที่ที่ปิดงาน']
  "duration" int [note:'ระยะเวลาในการดำเนินการ (วัน) : วันที่ปิด - วันที่รับเรื่อง']
  "closed_description" ntext [note:'รายละเอียดในการปิดงาน']
  "created_by" nvarchar(50) [note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [note:'วันที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [note:'วันที่ที่ปรับปรุงข้อมูล']
  "status" varchar(1) [note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']
  note:"ตารางเก็บรายละเอียดการรบกวน"
Indexes {
  id [pk]
}
}

Table "dbo"."EMF_Measurement_Report" {
  "id" bigint [not null, increment,note:'ID. ของ EMF Measurement Report']
  "report_year" int [not null,note:'ปีของข้อมูลการตรวจวัด']
  "report_month" int [not null,note:'เดือนของข้อมูลการตรวจวัด']
  "report_date" int [not null,note:'วันที่ของข้อมูลการตรวจวัด']
  "report_quarter" int [not null,note:'ไตรมาสของข้อมูลการตรวจวัด']
  "selection" nvarchar(100) [note:'เก็บข้อมูล Text "Unchecked,checked"']
  "measured_time" datetime [note:'วันที่เวลาที่ทำการตรวจสอบข้อมูล']
  "service_name" nvarchar(50) [note:'ชื่อ Service ของข้อมูลการตรวจวัด']
  "start_Hz" int [note:'ความถี่ (Hz) เริ่มต้นที่ทำการตรวจวัด']
  "stop_Hz" int [note:'ความถี่ (Hz) สิ้นสุดที่ทำการตรวจวัด']
  "original_file_name" nvarchar(100) [note:'ชื่อของไฟล์ต้นฉบับที่นำเข้าข้อมูล']
  "new_file_name" nvarchar(100) [note:'ชื่อของไฟล์ที่นำเข้าข้อมูลสำเร็จ อัพเดทชื่อใหม่ ต่อท้ายด้วย_yyMMddHHmm']
  "files_path" nvarchar(500) [note:'ชื่อ path ที่เก็บไฟล์หลังจากนำเข้าข้อมูลสำเร็จหรือ Fail(แยกเก็บ)']
  "created_date" datetime [note:'วันเวลาที่สร้างข้อมูล']
  note:"ตารางเก็บข้อมูล ( Header ) การกำกับดูแลความปลอดภัยต่อสุขภาพ"
Indexes {
  id [pk]
}
}

Table "dbo"."EMF_Measurement_Report_Detail" {
  "id" bigint [not null, increment,note:'ID. ของ EMF_Measurement_Report_Detail']
  "emf_measurement_report_id" bigint [not null,note:'ID. ของ EMF_Measurement_Report (FK.)']
  "max_V/m" decimal(20,4) [note:'ค่า Max ของการตรวจวัดโดยคำนวณจาก V/m']
  "avg_V/m" decimal(20,4) [note:'ค่า Avg ของการตรวจวัดโดยคำนวณจาก V/m']
  "rms_V/m" decimal(20,4) [note:'ค่า Rms ของการตรวจวัดโดยคำนวณจาก V/m']
  "limit_V/m" decimal(20,4) [note:'ค่า Limit ของการตรวจวัดโดยคำนวณจาก V/m']
  "max_percent" decimal(20,4) [note:'ค่า Max ของการตรวจวัดแบบ %']
  "avg_percent" decimal(20,4) [note:'ค่า Avg ของการตรวจวัดแบบ %']
  "rms_percent" decimal(20,4) [note:'ค่า Rms ของการตรวจวัดแบบ %']
  "max_mA/m" decimal(20,4) [note:'ค่า Max ของการตรวจวัดโดยคำนวณจาก mA/m']
  "avg_mA/m" decimal(20,4) [note:'ค่า Avg ของการตรวจวัดโดยคำนวณจาก mA/m']
  "rms_mA/m" decimal(20,4) [note:'ค่า Rms ของการตรวจวัดโดยคำนวณจาก mA/m']
  "max_mW/m" decimal(20,4) [note:'ค่า Max ของการตรวจวัดโดยคำนวณจาก mW/m']
  "avg_mW/m" decimal(20,4) [note:'ค่า Avg ของการตรวจวัดโดยคำนวณจาก mW/m']
  "rms_mW/m" decimal(20,4) [note:'ค่า Rms ของการตรวจวัดโดยคำนวณจาก mW/m']
  "created_date" datetime [note:'วันเวลาที่สร้างข้อมูล']
  note:"ตารางเก็บข้อมูล ( Detail ) การกำกับดูแลความปลอดภัยต่อสุขภาพ"
Indexes {
  id [pk]
}
}

Table "dbo"."Health_Safety_Test_Plan" {
  "id" bigint [not null, increment,note:'']
  "region_id" int [not null,note:'ID. ของ Region (FK.)']
  "area_id" int [not null,note:'ID. ของ Area (FK.)']
  "report_year" int [not null,note:'ปีของข้อมูลแผนการดำเนินการ']
  "description" nvarchar(50) [note:'คำอธิบาย']
  "actual_01" int [null,note:'แผนการทดสอบเดือน ม.ค.']
  "result_01" int [null,note:'ผลการทดสอบเดือน ม.ค.']
  "actual_02" int [null,note:'แผนการทดสอบเดือน ก.พ.']
  "result_02" int [null,note:'ผลการทดสอบเดือน ก.พ.']
  "actual_03" int [null,note:'แผนการทดสอบเดือน มี.ค.']
  "result_03" int [null,note:'ผลการทดสอบเดือน มี.ค.']
  "actual_04" int [null,note:'แผนการทดสอบเดือน เม.ย.']
  "result_04" int [null,note:'ผลการทดสอบเดือน เม.ย.']
  "actual_05" int [null,note:'แผนการทดสอบเดือน พ.ค.']
  "result_05" int [null,note:'ผลการทดสอบเดือน พ.ค.']
  "actual_06" int [null,note:'แผนการทดสอบเดือน มิ.ย.']
  "result_06" int [null,note:'ผลการทดสอบเดือน มิ.ย.']
  "actual_07" int [null,note:'แผนการทดสอบเดือน ก.ค.']
  "result_07" int [null,note:'ผลการทดสอบเดือน ก.ค.']
  "actual_08" int [null,note:'แผนการทดสอบเดือน ส.ค.']
  "result_08" int [null,note:'ผลการทดสอบเดือน ส.ค.']
  "actual_09" int [null,note:'แผนการทดสอบเดือน ก.ย.']
  "result_09" int [null,note:'ผลการทดสอบเดือน ก.ย.']
  "actual_10" int [null,note:'แผนการทดสอบเดือน ต.ค.']
  "result_10" int [null,note:'ผลการทดสอบเดือน ต.ค.']
  "actual_11" int [null,note:'แผนการทดสอบเดือน พ.ย.']
  "result_11" int [null,note:'ผลการทดสอบเดือน พ.ย.']
  "actual_12" int [null,note:'แผนการทดสอบเดือน ธ.ค.']
  "result_12" int [null,note:'ผลการทดสอบเดือน ธ.ค.']
  "original_file_name" nvarchar(100) [note:'ชื่อของไฟล์ต้นฉบับที่นำเข้าข้อมูล']
  "new_file_name" nvarchar(100) [note:'ชื่อของไฟล์ที่นำเข้าข้อมูลสำเร็จ อัพเดทชื่อใหม่ ต่อท้ายด้วย_yyMMddHHmm']
  "file_path" nvarchar(500) [note:'ชื่อ path ที่เก็บไฟล์หลังจากนำเข้าข้อมูลสำเร็จหรือ Fail(แยกเก็บ)']
  "created_by" nvarchar(50) [note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" int [note:'วันเวลาที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [note:'ชื่อของผู้แก้ไขข้อมูล']
  "modified_date" int [note:'วันเวลาที่แก้ไขข้อมูล']
  note:"ตารางเก็บข้อมูลแผนการกำกับดูแลความปลอดภัยต่อสุขภาพ"
Indexes {
  id [pk]
}
}

Table "dbo"."Info_Area" {
  "id" int [not null, increment,note:'ID. ของเขตพื้นที่ในกสทช.']
  "region_id" int [not null,note:'ID. ของภาคในกสทช. (FK.)']
  "name_th" nvarchar(50) [not null,note:'ชื่อภาษาไทยของพื้นที่ในกสทช.']
  "name_en" nvarchar(50) [note:'ชื่อภาษาอังกฤษของพื้นที่ในกสทช.']
  "created_by" nvarchar(50) [note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [note:'วันที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [note:'ชื่อของผู้แก้ไขข้อมูล']
  "modified_date" datetime [note:'วันเวลาที่แก้ไขข้อมูล']
  "deleted_by" nvarchar(50) [note:'ชื่อของผู้ลบข้อมูล']
  "deleted_date" datetime [note:'วันเวลาที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']
  note:"ตารางเก็บข้อมูลเขตของ กสทช."
Indexes {
  id [pk]
}
}

Table "dbo"."Info_Broadcast_Station" {
  "id" bigint [not null, increment,note:'ID. ของสถานีวิทยุ']
  "chk_ID" int [note:'รหัส ChkID']
  "transaction_date" datetime [note:'วันที่ของข้อมูล']
  "checked_date" datetime [note:'วันที่ที่ตรวจสอบ']
  "region_id" int [not null,note:'รหัสของภาคในกสทช. (FK.)']
  "region_name" nvarchar(50) [note:'ชื่อของภาคในกสทช.']
  "area_id" int [not null,note:'รหัสของเขตในกสทช. (FK.)']
  "area_name" nvarchar(50) [note:'ชื่อของเขตในกสทช']
  "station" nvarchar(50) [note:'ลักษณะของสถานี']
  "station_type_id" int [not null,note:'ID. ของประเภทสถานี (FK.)']
  "station_type_name" nvarchar(50) [note:'ชื่อของประเภทของสถานี']
  "station_code" nvarchar(10) [note:'รหัสของสถานี']
  "station_name" nvarchar(100) [note:'ชื่อของสถานี']
  "frequency" decimal(10,4) [note:'ความถี่ (MHz)']
  "license_no" nvarchar(20) [note:'เลขที่ใบอนุญาต']
  "province_id" int [not null,note:'รหัสของจังหวัด (FK.)']
  "province_name" nvarchar(50) [note:'ชื่อของจังหวัด']
  "district_id" int [not null,note:'รหัสของอำเภอ / เขต (FK.)']
  "district_name" nvarchar(50) [note:'ขื่อของอำเภอ / เขต']
  "sub_district_id" int [note:'รหัสของตำบล / แขวง']
  "sub_district_name" nvarchar(50) [note:'ชื่อของตำบล / แขวง']
  "address" nvarchar(500) [note:'ที่ตั้งของสถานี']
  "latitude" decimal(12,9) [note:'ละติจูดของสถานี']
  "longitude" decimal(12,9) [note:'ลองจิจูดของสถานี']
  "tested_result" ntext [note:'ผลการทดสอบ']
  "station_status" nvarchar(50) [note:'สถานะของสถานี']
  "broadcase_start_time" time [note:'ระยะเวลาเริ่มต้นการออกอากาศ']
  "broadcast_end_time" time [note:'ระยะเวลาสิ้นสุดการออกอากาศ']
  "created_by" nvarchar(50) [note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [note:'วันที่ที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [note:'ชื่อของผู้ลบข้อมูล']
  "deleted_date" datetime [note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']
  note:"ตารางเก็บข้อมูลเสาส่งโทรศัพท์มือถือ"
Indexes {
  id [pk]
}
}

Table "dbo"."Info_Business_Type" {
  "id" int [not null, increment,note:'ID. ของประเภทกิจการ']
  "name_th" nvarchar(100) [not null,note:'ชื่อภาษาไทยของประเภทกิจการ']
  "name_en" nvarchar(100) [note:'ชื่อภาษาอังกฤษของประเภทกิจการ']
  "created_by" nvarchar(50) [note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [note:'วันที่ที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [note:'ชื่อของผู้บข้อมูล']
  "deleted_date" datetime [note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']
  note:"ตารางเก็บข้อมูลประเภทกิจการ"
Indexes {
  id [pk]
}
}

Table "dbo"."Info_Company_Type" {
  "id" int [not null, increment,note:'ID. ของประเภทหน่วยงาน']
  "name_th" nvarchar(100) [not null,note:'ชื่อภาษาไทยของประเภทหน่วยงาน']
  "name_en" nvarchar(100) [note:'ชื่อภาษาอังกฤษของประเภทหน่วยงาน']
  "created_by" nvarchar(50) [note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [note:'วันที่ที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [note:'ชื่อของผู้บข้อมูล']
  "deleted_date" datetime [note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']
  note:"ตารางเก็บข้อมูลประเภทบริษัท"
Indexes {
  id [pk]
}
}

Table "dbo"."Info_District" {
  "id" int [not null,note:'ID. ของอำเภอ / เขต']
  "province_id" int [not null,note:'ID. ของจังหวัด (FK.)']
  "name_th" nvarchar(50) [not null,note:'ชื่อภาษาไทยของอำเภอ / เขต']
  "name_en" nvarchar(50) [note:'ชื่อภาษาอังกฤษของอำเภอ / เขต']
  "sort_order_th" int [null,note:'ลำดับในการเรียงตามตัวอักษรภาษาไทย']
  "sort_order_en" int [null,note:'ลำดับในการเรียงตามตัวอักษรภาษาอังกฤษ']
  "created_by" nvarchar(50) [note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [note:'วันที่ที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [note:'ชื่อของผู้สร้างข้อมูล']
  "deleted_date" datetime [note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']
  note:"ตารางเก็บข้อมูลอำเภอ / เขต"
Indexes {
  id [pk]
}
}

Table "dbo"."Info_Disturbance_Status" {
  "id" int [not null, increment,note:'ID. ของสถานะการรบกวน']
  "name_th" nvarchar(100) [not null,note:'ชื่อภาษาไทยของสถานะการรบกวน']
  "name_en" nvarchar(100) [note:'ชื่อภาษาอังกฤษของสถานะการรบกวน']
  "created_by" nvarchar(50) [note:'ชื่อของผูสร้างข้อมูล']
  "created_date" datetime [note:'วันที่ที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [note:'ชื่อของผู้ลบข้อมูล']
  "deleted_date" datetime [note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']
  note:"ตารางเก็บข้อมูลสถานะของการรบกวน"
Indexes {
  id [pk]
}
}

Table "dbo"."Info_Disturbance_Type" {
  "id" int [not null, increment,note:'ID. ของประเภทการรบกวน']
  "name_th" nvarchar(100) [not null,note:'ชื่อภาษาไทยของประเภทการรบกวน']
  "name_en" nvarchar(100) [note:'ชื่อภาษาอังกฤษของประเภทการรบกวน']
  "created_by" nvarchar(50) [note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [note:'วันที่ที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [note:'ชื่อของผู้ลบข้อมูล']
  "deleted_date" datetime [note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']
  note:"ตารางเก็บข้อมูลประเภทการรบกวน"
Indexes {
  id [pk]
}
}

Table "dbo"."Info_Geography" {
  "id" int [not null, increment,note:'ID. ของภาคในประเทศ']
  "name_th" nvarchar(50) [not null,note:'ชื่อภาษาไทยของภาคในประเทศ']
  "name_en" nvarchar(50) [note:'ชื่อภาษาอังกฤษของภาคในประเทศ']
  "created_by" nvarchar(50) [note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [note:'วันที่ที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [note:'ชื่อของผู้ลบข้อมูล']
  "deleted_date" datetime [note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']
  note:"ตารางเก็บข้อมูลภาคตามภูมิศาสตร์"
Indexes {
  id [pk]
}
}

Table "dbo"."Info_License_Type" {
  "id" int [not null, increment,note:'ID. ของประเภท.ใบอนุญาต']
  "name_th" nvarchar(100) [not null,note:'ชื่อภาษาไทยของประเภทใบอนุญาต']
  "name_en" nvarchar(100) [note:'ชื่อภาษาอังกฤษของประเภทใบอนุญาต']
  "created_by" nvarchar(50) [note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [note:'วันที่ที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [note:'ชื่อของผู้บข้อมูล']
  "deleted_date" datetime [note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']
  note:"ตารางเก็บข้อมูลประเภทใบอนุญาต"
Indexes {
  id [pk]
}
}

Table "dbo"."Info_Other_Station" {
  "id" bigint [not null, increment,note:'ID. ของสถานี']
  "owner_type_id" int [not null,note:'ID. ของประเภทผู้ครอบครอง (FK.)']
  "owner_type_name" nvarchar(100) [note:'ชื่อของประเภทผู้ครอบครอง']
  "region_id" int [not null,note:'รหัสของภาคในกสทช. (FK.)']
  "region_name" nvarchar(50) [note:'ชื่อของภาคในกสทช.']
  "area_id" int [note:'รหัสของเขตในกสทช. (FK.)']
  "area_name" nvarchar(50) [not null,note:'ชื่อของเขตในกสทช.']
  "station_type_id" int [not null,note:'ID. ของประเภทสถานี (FK.)']
  "station_type_name" nvarchar(50) [not null,note:'ชื่อของประเภทสถานี']
  "station_code" nvarchar(10) [not null,note:'รหัสของสถานี']
  "station_name" nvarchar(100) [not null,note:'ชื่อของสถานี']
  "frequency" nvarchar(50) [not null,note:'ความถี่ (MHz)']
  "ฺbusiness_name" nvarchar(255) [not null,note:'ชื่อของผู้ประกอบการ']
  "company_type_id" int [not null,note:'ID. ของประเภทหน่วยงาน (FK.)']
  "company_type_name" nvarchar(100) [not null,note:'ชื่อของประเภทหน่วยงาน']
  "license_type_id" int [not null,note:'ID. ของประเภทใบอนุญาต (FK.)']
  "license_type_name" nvarchar(100) [not null,note:'ชื่อของประเภทใบอนุญาต']
  "license_no" nvarchar(20) [not null,note:'เลขที่ใบอนุญาต']
  "license_date" datetime [not null,note:'วันที่ที่ออกใบอนุญาต']
  "province_id" int [not null,note:'รหัสของจังหวัด (FK.)']
  "province_name" nvarchar(50) [not null,note:'ชื่อของจังหวัด']
  "district_id" int [not null,note:'รหัสของอำเภอ / เขต (FK.)']
  "district_name" nvarchar(50) [not null,note:'ขื่อของอำเภอ / เขต']
  "sub_district_id" int [not null,note:'รหัสของตำบล / แขวง']
  "sub_district_name" nvarchar(50) [not null,note:'ชื่อของตำบล / แขวง']
  "address" nvarchar(500) [not null,note:'ที่ตั้งของสถานี']
  "latitude" decimal(12,9) [not null,note:'ละติจูดของสถานี']
  "longitude" decimal(12,9) [not null,note:'ลองจิจูดของสถานี']
  "contract_name" nvarchar(100) [not null,note:'ชื่อผู้ประสานงาน']
  "contract_telephone" nvarchar(50) [not null,note:'เบอร์โทรสำหรับติดต่อ']
  "altitude_above_sea_level" int [not null,note:'ความสูงจากระดับน้ำทะเล (M)']
  "aerial_type" nvarchar(100) [not null,note:'ชนิดสายอากาศ']
  "expansion_rate_of_aerial" decimal(10,2) [not null,note:'อัตราการขยายเสาอากาศ (DBI)']
  "sending" int [not null,note:'กำลังส่ง (W)']
  "height_of_aerial" int [not null,note:'ความสูงของเสาอากาศ (M)']
  "test_of_frequency" decimal(10,4) [not null,note:'ความถี่ที่วัดได้ (MHz)']
  "broadcast_start_time" time [not null,note:'ระยะเวลาเริ่มต้นการออกอากาศ']
  "broadcast_end_time" time [not null,note:'ระยะเวลาสิ้นสุดการออกอากาศ']
  "created_by" nvarchar(50) [not null,note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [not null,note:'วันที่ที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [not null,note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [not null,note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [not null,note:'ชื่อของผู้บข้อมูล']
  "deleted_date" datetime [not null,note:'วันที่ที่ลบข้อมูล']
  "Status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']
  note:"ตารางเก็บข้อมูล อปท. , มูลนิธิ , วิทยุชุมชน"
Indexes {
  id [pk]
}
}

Table "dbo"."Info_Owner_Type" {
  "id" int [not null, increment,note:'ID. ของประเภทผู้ครอบครอง']
  "name_th" nvarchar(100) [not null,note:'ชื่อภาษาไทยของประเภทผู้ครอบครอง']
  "name_en" nvarchar(100) [not null,note:'ชื่อภาษาอังกฤษของประเภทผู้ครอบครอง']
  "created_by" nvarchar(50) [not null,note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [not null,note:'วันที่ที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [not null,note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [not null,note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [not null,note:'ชื่อของผู้ลบข้อมูล']
  "deleted_date" datetime [not null,note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']
  note:"ตารางเก็บข้อมูลประเภทเจ้าของกิจการ"
Indexes {
  id [pk]
}
}

Table "dbo"."Info_Province" {
  "id" int [not null,note:'ID. ของจังหวัด']
  "geography_id" int [not null,note:'ID. ของภูมิภาค (FK.)']
  "name_th" nvarchar(50) [not null,note:'ชื่อภาษาไทยของจังหวัด']
  "name_en" nvarchar(50) [not null,note:'ชื่อภาษาอังกฤษของจังหวัด']
  "sort_order_th" int [null,note:'ลำดับในการเรียงตามตัวอักษรภาษาไทย']
  "sort_order_en" int [null,note:'ลำดับในการเรียงตามตัวอักษรภาษาอังกฤษ']
  "created_by" nvarchar(50) [not null,note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [not null,note:'วันที่ที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [not null,note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [not null,note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [not null,note:'ชื่อของผู้ลบข้อมูล']
  "deleted_date" datetime [not null,note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']
  note:"ตารางเก็บข้อมูลจังหวัด"
Indexes {
  id [pk]
}
}

Table "dbo"."Info_Radio_Station" {
  "id" int [not null, increment,note:'ID. ของสถานีวิทยุการจายเสียง']
  "name_th" nvarchar(50) [not null,note:'ชื่อภาษาไทยของสถานีวิทยุการจายเสียง']
  "name_en" nvarchar(50) [not null,note:'ชื่อภาษาอังกฤษของสถานีวิทยุการจายเสียง']
  "station_unit" nvarchar(10) [not null,note:'หน่วยนับของสถานีวิทยุการจายเสียง']
  "created_by" nvarchar(50) [not null,note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [not null,note:'วันที่ที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [not null,note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [not null,note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [not null,note:'ชื่อของผู้ลบข้อมูล']
  "deleted_date" datetime [not null,note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']
  note:"ตารางเก็บข้อมูลสถานีวิทยุ"
Indexes {
  id [pk]
}
}

Table "dbo"."Info_Region" {
  "id" int [not null, increment,note:'ID. ของภาคในกสทช.']
  "name_th" nvarchar(50) [not null,note:'ชื่อภาษาไทยของภาคในกสทช']
  "name_en" nvarchar(50) [not null,note:'ชื่อภาษาอังกฤษของภาคในกสทช']
  "created_by" nvarchar(50) [not null,note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [not null,note:'วันที่ที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [not null,note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [not null,note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [not null,note:'ชื่อของผู้ลบข้อมูล']
  "deleted_date" datetime [not null,note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']
   note:"ตารางเก็บข้อมูลภาคของ กสทช."
Indexes {
  id [pk]
}
}

Table "dbo"."Info_Station_Type" {
  "id" int [not null, increment,note:'ID. ของประเภทสถานี']
  "name_th" nvarchar(100) [not null,note:'ชื่อภาษาไทยของประเภทสถานี']
  "name_en" nvarchar(100) [not null,note:'ชื่อภาษาอังกฤษของประเภทสถานี']
  "created_by" nvarchar(50) [not null,note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [not null,note:'วันที่ที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [not null,note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [not null,note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [not null,note:'ชื่อของผู้บข้อมูล']
  "deleted_date" datetime [not null,note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']
   note:"ตารางเก็บข้อมูลประเภทสถานี"
Indexes {
  id [pk]
}
}

Table "dbo"."Info_Station_SubType" {
  "id" int [not null, increment,note:'ID. ของประเภทสถานีย่อย']
  "station_type_id" int [not null,note:'ID. ของประเภทสถานี']
  "name_th" nvarchar(100) [not null,note:'ชื่อภาษาไทยของประเภทสถานี']
  "name_en" nvarchar(100) [not null,note:'ชื่อภาษาอังกฤษของประเภทสถานี']
  "created_by" nvarchar(50) [not null,note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [not null,note:'วันที่ที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [not null,note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [not null,note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [not null,note:'ชื่อของผู้บข้อมูล']
  "deleted_date" datetime [not null,note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']
   note:"ตารางเก็บข้อมูลประเภทสถานี"
Indexes {
  id [pk]
}
}

Table "dbo"."Info_Sub_District" {
  "id" int [not null,note:'ID. ของตำบล / แขวง']
  "province_id" int [not null,note:'ID. ของจังหวัด (FK.)']
  "district_id" int [not null,note:'ID. ของอำเภอ / เขต (FK.)']
  "name_th" nvarchar(50) [not null,note:'ชื่อภาษาไทยของตำบล / แขวง']
  "name_en" nvarchar(50) [not null,note:'ชื่อภาษาอังกฤษของตำบล / แขวง']
  "sort_order_th" int [null,note:'ลำดับในการเรียงตามตัวอักษรภาษาไทย']
  "sort_order_en" int [null,note:'ลำดับในการเรียงตามตัวอักษรภาษาอังกฤษ']
  "created_by" nvarchar(50) [not null,note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [not null,note:'วันที่ที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [not null,note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [not null,note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [not null,note:'ชื่อของผู้ลบข้อมูล']
  "deleted_date" datetime [not null,note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']
   note:"ตารางเก็บข้อมูลตำบล / แขวง"
Indexes {
  id [pk]
}
}

Table "dbo"."Info_Zipcode" {
  "id" int [not null, increment,note:'ID. ของรหัสไปรษณีย์']
  "province_id" int [not null,note:'ID. ของจังหวัด (FK.)']
  "district_id" int [not null,note:'ID. ของอำเภอ (FK.)']
  "sub_district_id" int [not null,note:'ID. ของตำบล / แขวง (FK.)']
  "code" varchar(5) [not null,note:'รหัสไปรษณีย์']
  "created_by" nvarchar(50) [not null,note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" datetime [not null,note:'วันที่ที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [not null,note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" datetime [not null,note:'วันที่ที่ปรับปรุงข้อมูล']
  "deleted_by" nvarchar(50) [not null,note:'ชื่อของผู้ลบข้อมูล']
  "deleted_date" datetime [not null,note:'วันที่ที่ลบข้อมูล']
  "status" varchar(1) [not null,note:'สถานะของข้อมูล ( A = Active, I = Inactive, D = Delete )']
   note:"ตารางเก็บข้อมูลรหัสไปรษณีย์"
Indexes {
  id [pk]
}
}

Table "dbo"."Radio_Emission_Test_Plan" {
  "id" bigint [not null, increment,note:'ID. ของ EMF Measurement Report']
  "region_id" int [not null,note:'ID. ของ Region (FK.)']
  "area_id" int [not null,note:'ID. ของ Area (FK.)']
  "report_year" int [not null,note:'ปีของข้อมูลแผนการดำเนินการ']
  "station_type_id" int [not null,note:'ID. ของ Info_Station_Type (FK.)']
  "actual_01" int [null,note:'แผนการทดสอบเดือน ม.ค.']
  "result_01" int [null,note:'ผลการทดสอบเดือน ม.ค.']
  "actual_02" int [null,note:'แผนการทดสอบเดือน ก.พ.']
  "result_02" int [null,note:'ผลการทดสอบเดือน ก.พ.']
  "actual_03" int [null,note:'แผนการทดสอบเดือน มี.ค.']
  "result_03" int [null,note:'ผลการทดสอบเดือน มี.ค.']
  "actual_04" int [null,note:'แผนการทดสอบเดือน เม.ย.']
  "result_04" int [null,note:'ผลการทดสอบเดือน เม.ย.']
  "actual_05" int [null,note:'แผนการทดสอบเดือน พ.ค.']
  "result_05" int [null,note:'ผลการทดสอบเดือน พ.ค.']
  "actual_06" int [null,note:'แผนการทดสอบเดือน มิ.ย.']
  "result_06" int [null,note:'ผลการทดสอบเดือน มิ.ย.']
  "actual_07" int [null,note:'แผนการทดสอบเดือน ก.ค.']
  "result_07" int [null,note:'ผลการทดสอบเดือน ก.ค.']
  "actual_08" int [null,note:'แผนการทดสอบเดือน ส.ค.']
  "result_08" int [null,note:'ผลการทดสอบเดือน ส.ค.']
  "actual_09" int [null,note:'แผนการทดสอบเดือน ก.ย.']
  "result_09" int [null,note:'ผลการทดสอบเดือน ก.ย.']
  "actual_10" int [null,note:'แผนการทดสอบเดือน ต.ค.']
  "result_10" int [null,note:'ผลการทดสอบเดือน ต.ค.']
  "actual_11" int [null,note:'แผนการทดสอบเดือน พ.ย.']
  "result_11" int [null,note:'ผลการทดสอบเดือน พ.ย.']
  "actual_12" int [null,note:'แผนการทดสอบเดือน ธ.ค.']
  "result_12" int [null,note:'ผลการทดสอบเดือน ธ.ค.']
  "original_file_name" nvarchar(100) [not null,note:'ชื่อของไฟล์ต้นฉบับที่นำเข้าข้อมูล']
  "new_file_name" nvarchar(100) [not null,note:'ชื่อของไฟล์หลังจากที่นำเข้าข้อมูล']
  "file_path" nvarchar(500) [not null,note:'ชื่อ path ที่เก็บไฟล์หลังจากนำเข้าข้อมูล']
  "created_by" nvarchar(50) [not null,note:'ชื่อของผู้สร้างข้อมูล']
  "created_date" int [not null,note:'วันที่ที่สร้างข้อมูล']
  "modified_by" nvarchar(50) [not null,note:'ชื่อของผู้ปรับปรุงข้อมูล']
  "modified_date" int [not null,note:'วันที่ที่ปรับปรุงข้อมูล']
   note:"ตารางเก็บข้อมูลแผนการตรวจสอบมาตรฐานการแพร่"
Indexes {
  id [pk]
}
}

Table "dbo"."TCI_Occupancy_Report" {
  "id" bigint [not null, increment,note:'ID. ของ TCI_Occupancy_Report']
  "report_year" int [not null,note:'ปีของข้อมูลการครอบครอง']
  "report_month" int [not null,note:'เดือนของข้อมูลการครอบครอง']
  "report_date" int [not null,note:'วันที่ของข้อมูลการครอบครอง']
  "report_quarter" int [not null,note:'ไตรมาสของข้อมูลการครอบครอง']
  "task_id" int [not null,note:'ค่า TaskID ของข้อมูลการครอบครอง']
  "storage_interval" nvarchar(20) [not null,note:'ค่า Storeage Interval ของข้อมูลการครอบครอง']
  "operator_id" nvarchar(100) [not null,note:'ค่า Operator ID. ของข้อมูลการครอบครอง']
  "message_length" int [not null,note:'ค่า Message Length ของข้อมูลการครอบครอง']
  "start_time" datetime [not null,note:'เวลาเริ่มต้นของของข้อมูลการครอบครอง']
  "stop_time" datetime [not null,note:'เวลาสิ้นสุดของข้อมูลการครอบครอง']
  "threshold_method" nvarchar(100) [not null,note:'ค่าของ ThresholdMethod']
  "duration" nvarchar(100) [not null,note:'ระยะเวลาในการดำเนินการ']
  "station_name" nvarchar(100) [not null,note:'ชื่อของสถานี']
  "all_single_channels" char(1) [not null,note:'ค่าของ AllSingleChannels (Y/N)']
  "latitude" decimal(12,9) [not null,note:'ละติจูดของสถานี']
  "longitude" decimal(12,9) [not null,note:'ลองจิจูดของสถานี']
  "antenna" nvarchar(50) [not null,note:'รายละเอียดของ Antenna']
  "polarization" nvarchar(20) [not null,note:'รายละเอียดของ Polarization']
  "original_file_name" nvarchar(100) [not null,note:'ชื่อของไฟล์ต้นฉบับที่นำเข้าข้อมูล']
  "new_file_name" nvarchar(100) [not null,note:'ชื่อของไฟล์หลังจากที่นำเข้าข้อมูล']
  "files_path" nvarchar(500) [not null,note:'ชื่อ path ที่เก็บไฟล์หลังจากนำเข้าข้อมูล']
  "created_date" datetime [not null,note:'วันที่ที่สร้างข้อมูล']
   note:"ตารางเก็บข้อมูล ( Header ) การตรวจสอบการครอบครองความถี่"
Indexes {
  id [pk]
}
}

Table "dbo"."TCI_Occupancy_Report_Detail" {
  "id" bigint [not null, increment,note:'ID. ของ TCI_Occupancy_Report_Detail']
  "tci_occupancy_report_id" bigint [not null,note:'ID. ของ TCI_Occupancy_Report (FK.)']
  "band" int [not null,note:'เลขของ Band ที่นำเข้าข้อมูล TCI']
  "start_frequency_MHz" int [not null,note:'ความถี่เริ่มต้นในการวัดผล (MHz)']
  "stop_frequency_MHz" int [not null,note:'ความถี่สิ้นสุดในการวัดผล (MHz)']
  "bandwidth_kHz" decimal(20,4) [not null,note:'ค่าของ Bandwidth (kHz)']
  "channel_no" int [not null,note:'หมายเลขของ Channel ที่ทำการตรวจวัด']
  "frequency_MHz" decimal(20,4) [not null,note:'ค่าของ Frequency(MHz)']
  "maximum_occupancy_percent" int [not null,note:'ค่าของ MaximumOccupancy %']
  "average_occupancy_percent" int [not null,note:'ค่าของ AverageOccupancy %']
  "maximum_field_strength_dBuV/m" int [not null,note:'ค่าของ MaximumFieldStrength(dBuV/m)']
  "average_field_strength_dBuV/m" int [not null,note:'ค่าของ AverageFieldStrength(dBuV/m)']
  "created_date" datetime [not null,note:'วันที่ที่สร้างข้อมูล']
  note:"ตารางเก็บข้อมูล ( Detail ) การตรวจสอบการครอบครองความถี่"
Indexes {
  id [pk]
}
}

Table "dbo"."Frequency_Emission_Report" {
  "id" int [not null, increment,note:'ID. ของ Frequency_Emission_Report']
  "chkid" int [not null,note:'ID การตรวจสอบของ oper fieldname ChkID']
  "add_date" datetime [note:'วันที่บันทึกจาก oper fieldname DtAdd']
  "chk_date" datetime [note:'วันที่ตรวจสอบจาก oper fieldname DtTest']
  "region_id" int [not null,note:'ID. ของภาคในกสทช.[FK]']
  "area_id" int [not null,note:'ID. ของเขตพื้นที่ในกสทช. [FK]']
  "station_type_id" int [not null,note:'ID. ของ Info_Station_Type (FK.)']
  "stn_type" nvarchar(250) [null,note:'สถานี oper fieldname StnType']
  "station_subtype_id" int [not null,note:'ID. ของ Info_Station_SubType (FK.)']
  "stn_subtype" nvarchar(250) [null,note:'ประเภทสถานี oper fieldname StnSubType']
  "stn_code" nvarchar(250) [null,note:'รหัสสถานี oper fieldname StnCode']
  "station_name" nvarchar(250) [null,note:'ชื่อสถานี  oper fieldname StaNaG' ]
  "frequency_MHz" nvarchar(50) [null,note:'ความถี่ oper fieldname FreqMhzG']
  "stn_license" nvarchar(50) [null,note:'เลขที่ใบอนุญาต oper fieldname StaNoG']
  "province" nvarchar(200) [null,note:'ชื่อจังหวัด oper fieldname Province']
  "aumphoe" nvarchar(200) [null,note:'ชื่ออำเภอ oper fieldname Aumphoe']
  "tambol" nvarchar(200) [null,note:'ชื่อตำบล oper fieldname Tambol']
  "sta_locg" nvarchar(450) [null,note:'ที่ตั้งสถานี oper fieldname StaLocG']
  "opinion_det" nvarchar(250) [null,note:'ผลการตรวจสอบ oper fieldname OpinionDet']
  "equ_name" nvarchar(max) [null,note:'เครื่องมือวัด oper fieldname EquNames']
  "docnfno_disp" nvarchar(250) [null,note:'หนังสือแจ้งเตือน oper fieldname DocNFNo_Disp ']
  "docnfno_date" nvarchar(250) [null,note:'หนังสือแจ้งเตือนวันที่ oper fieldname DtDocNF_Disp']
  "approve_status" nvarchar(11) [null,note:'สถานะ oper fieldname ApvStatus']
  "created_date" datetime [not null,note:'วันที่ที่สร้างข้อมูล']
  note:"ตารางเก็บข้อมูลการตรวจสอบมาตรฐานการแพร่ [ข้อมูลจาก oper Table Name tbF11_RadProp]"
  Indexes {
  id [pk]
}
}

Table "dbo"."Frequency_Disturbance_Report" {
"id" int [not null, increment,note:'ID. ของ Frequency_Disturbance_Report']
"chkid" int [not null,note:'ID การตรวจสอบของ oper fieldname ChkID']
"add_date" datetime [note:'วันที่บันทึกจาก oper fieldname DtAdd']
"region_id" int [not null,note:'ID. ของภาคในกสทช.[FK]']
"area_id" int [not null,note:'ID. ของเขตพื้นที่ในกสทช. [FK]']
"station_name" nvarchar(100) [null,note:'ชื่อสถานีตรวจสอบ oper fieldname StaNaG']
"stn_license" nvarchar(100) [null,note:'เลขที่ใบอนุญาต oper fieldname StaNoG']
"province" nvarchar(100) [null,note:'ชื่อจังหวัด oper fieldname Province']
"aumphoe" nvarchar(100) [null,note:'ชื่ออำเภอ oper fieldname Aumphoe']
"tambol" nvarchar(250) [null,note:'ชื่อตำบล oper fieldname Tambol']
"sta_locg" nvarchar(max) [null,note:'ที่ตั้ง oper fieldname StaLocG']
"freq_src_type" nvarchar(200) [null,note:'ประเภทแหล่งกำเนิด oper fieldname FreqSrcType']
 "freq_mhzg" nvarchar(200) [null,note:'ความถี่ oper fieldname FreqMhzG']
 "diss_emitts" nvarchar(200) [null,note:'สาเหตุการรบกวน oper fieldname DisEmitts']
 "dist_rrk" nvarchar(200) [null,note:'รายละเอียดการรบกวน oper fieldname DistRrk']
 "dis_chk" nvarchar(500) [null,note:'ความเห็นผู้ตรวจ oper fieldname DisChk']
 "equ_names" nvarchar(max) [null,note:'เครื่องมือวัด oper fieldname EquNames']
 "dt_test" datetime [note:'วันที่ตรวจสอบ oper fieldname DtTest']
 "dt_rep" datetime [note:'วันที่รายงาน oper fieldname DtRep']
 "dt_apv" datetime [note:'วันที่อนุมัติ oper fieldname DtApv']
 "apv_status" nvarchar(11) [null,note:'สถานะ oper fieldname ApvStatus']
 "created_date" datetime [not null,note:'วันที่ที่สร้างข้อมูล']
 note:"ตารางเก็บข้อมูลการตรวจสอบแก้ไขการรบกวนคลื่นวิทยุ [ข้อมูลจาก oper Table Name tbF12_DistbRad ]"
 Indexes {
  id [pk]
}
}

Table "dbo"."Frequency_NotAllow_Report" {
  "id" int [not null, increment,note:'ID. ของ Frequency_NotAllow_Report']
  "chkid" int [not null,note:'ID การตรวจสอบของ oper fieldname ChkID']
  "chk_date" datetime [note:'วันที่ตรวจสอบจาก oper fieldname DtTest']
  "region_id" int [not null,note:'ID. ของภาคในกสทช.[FK]']
  "area_id" int [not null,note:'ID. ของเขตพื้นที่ในกสทช. [FK]']
  "station_name" nvarchar(250) [null,note:'ชื่อสถานี  oper fieldname StaNaG' ]
  "frequency_MHz" nvarchar(50) [null,note:'ความถี่ oper fieldname FreqMhzG']
  "province" nvarchar(200) [null,note:'ชื่อจังหวัด oper fieldname Province']
  "aumphoe" nvarchar(200) [null,note:'ชื่ออำเภอ oper fieldname Aumphoe']
  "tambol" nvarchar(200) [null,note:'ชื่อตำบล oper fieldname Tambol']
  "station_location" nvarchar(450) [null,note:'ที่ตั้งสถานี oper fieldname StaLocG']
  "equ_name" nvarchar(max) [null,note:'เครื่องมือวัด oper fieldname EquNames']
  "approve_status" nvarchar(11) [null,note:'สถานะ oper fieldname ApvStatus']
  "created_date" datetime [not null,note:'วันที่ที่สร้างข้อมูล']
  note:"ตารางเก็บข้อมูลการตรวจสอบความถี่ที่ไม่ได้รับอนุญาต [ข้อมูลจาก oper Table Name tbF13_NotAllow]"
  Indexes {
  id [pk]
}
}

Ref "Fk":"dbo"."Info_Region"."id" < "dbo"."Frequency_Emission_Report"."region_id"
Ref "Fk":"dbo"."Info_Area"."id" < "dbo"."Frequency_Emission_Report"."area_id"
Ref "FK":"dbo"."Info_Station_Type"."id" < "dbo"."Frequency_Emission_Report"."station_type_id"
Ref "FK":"dbo"."Info_Station_SubType"."id" < "dbo"."Frequency_Emission_Report"."station_subtype_id"


Ref "Fk":"dbo"."Info_Region"."id" < "dbo"."Frequency_Disturbance_Report"."region_id"
Ref "Fk":"dbo"."Info_Area"."id" < "dbo"."Frequency_Disturbance_Report"."area_id"

Ref "Fk":"dbo"."Info_Region"."id" < "dbo"."Frequency_NotAllow_Report"."region_id"
Ref "Fk":"dbo"."Info_Area"."id" < "dbo"."Frequency_NotAllow_Report"."area_id"


Ref "FKHealth_Saf953904":"dbo"."Info_Area"."id" < "dbo"."Health_Safety_Test_Plan"."area_id"

Ref "FKHealth_Saf855281":"dbo"."Info_Region"."id" < "dbo"."Health_Safety_Test_Plan"."region_id"

Ref "FKRadio_Emis890179":"dbo"."Info_Area"."id" < "dbo"."Radio_Emission_Test_Plan"."area_id"

Ref "FKRadio_Emis80993":"dbo"."Info_Region"."id" < "dbo"."Radio_Emission_Test_Plan"."region_id"

Ref "FKRadio_Emis238262":"dbo"."Info_Station_Type"."id" < "dbo"."Radio_Emission_Test_Plan"."station_type_id"

Ref "FKInfo_Zipco299713":"dbo"."Info_Province"."id" < "dbo"."Info_Zipcode"."province_id"

Ref "FKInfo_Zipco255546":"dbo"."Info_District"."id" < "dbo"."Info_Zipcode"."district_id"

Ref "FKArea_Provi574106":"dbo"."Info_Geography"."id" < "dbo"."Area_Province"."geography_id"

Ref "FKInfo_Sub_D858503":"dbo"."Info_Province"."id" < "dbo"."Info_Sub_District"."province_id"

Ref "FKInfo_Zipco177048":"dbo"."Info_Sub_District"."id" < "dbo"."Info_Zipcode"."sub_district_id" [update: cascade]

Ref "FKDisturbanc342409":"dbo"."Info_Business_Type"."id" < "dbo"."Disturbance_Report"."business_type_id"

Ref "FKDisturbanc708223":"dbo"."Info_Disturbance_Status"."id" < "dbo"."Disturbance_Report"."disturbance_status_id"

Ref "FKInfo_Sub_D902670":"dbo"."Info_District"."id" < "dbo"."Info_Sub_District"."district_id" [update: cascade]

Ref "FKInfo_Distr360426":"dbo"."Info_Province"."id" < "dbo"."Info_District"."province_id" [update: cascade]

Ref "FKInfo_Provi333697":"dbo"."Info_Geography"."id" < "dbo"."Info_Province"."geography_id" [update: cascade]

Ref "FKArea_Provi922664":"dbo"."Info_Province"."id" < "dbo"."Area_Province"."province_id" [update: cascade]

Ref "FKArea_Provi893606":"dbo"."Info_Area"."id" < "dbo"."Area_Province"."area_id"

Ref "FKDisturbanc670568":"dbo"."Info_Region"."id" < "dbo"."Disturbance_Report"."region_id"

Ref "FKInfo_Area396653":"dbo"."Info_Region"."id" < "dbo"."Info_Area"."region_id"

Ref "FKDisturbanc861381":"dbo"."Info_Area"."id" < "dbo"."Disturbance_Report"."area_id"

Ref "FKEMF_Measur160831":"dbo"."EMF_Measurement_Report"."id" < "dbo"."EMF_Measurement_Report_Detail"."emf_measurement_report_id"

Ref "FKTCI_Occupa427123":"dbo"."TCI_Occupancy_Report"."id" < "dbo"."TCI_Occupancy_Report_Detail"."tci_occupancy_report_id"

Ref "FKStnType":"dbo"."Info_Station_Type"."id" < "dbo"."Info_Station_SubType"."station_type_id"
